name: Swift CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.9"

      - name: Install xcresultparser
        run: |
          brew tap a7ex/homebrew-formulae
          brew install xcresultparser

      - name: Test iOS 16
        run: xcodebuild test -scheme PKSNavigation -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.4' -derivedDataPath /tmp/build -enableCodeCoverage YES

      - name: Test iOS 17
        run: xcodebuild test -scheme PKSNavigation -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' -derivedDataPath /tmp/build -enableCodeCoverage YES

      - name: Test iOS 18
        run: xcodebuild test -scheme PKSNavigation -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.0' -derivedDataPath /tmp/build -enableCodeCoverage YES

      # TODO: Merge coverage reports and upload to Codecov
      # - name: Merge coverage reports

      
      - name: Generate coverage report
        run: |
          xcresultparser -o cobertura /tmp/build/Logs/Test/Test-*.xcresult > cobertura.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./cobertura.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
